export const blogTags: string[] = [
  'Technology',
  'Programming',
  'JavaScript',
  'Python',
  'Web Development',
  'React',
  'Node.js',
  'AI',
  'Machine Learning',
  'Startups',
  'Productivity',
  'Mental Health',
  'Travel',
  'Food',
  'Lifestyle',
  'Fitness',
  'Health',
  'Finance',
  'Investing',
  'Personal Growth',
  'Books',
  'Education',
  'Design',
  'UI/UX',
  'Photography',
  'Marketing',
  'SEO',
  'Freelancing',
  'Remote Work',
  'Career',
  'Writing',
  'Blogging Tips',
  'Entertainment',
  'Movies',
  'Gaming',
  'Mobile Apps',
  'Cybersecurity',
  'Cloud Computing',
  'Data Science',
  'DevOps',
  'Open Source',
];
